class MyClass {
public:
    MyClass() = default; // Ask the compiler to generate the default constructor
    ~MyClass() = default; // Ask the compiler to generate the default destructor
};

int main() {
    MyClass obj; // Default constructor is generated by the compiler
    // Destructor is called automatically when obj goes out of scope
    return 0;
}
