class Complex {
public:
    Complex(double real, double imag) : real_(real), imag_(imag) {}
    
    // Default constructor (with no arguments) is deleted
     Complex() = default;
    
    // Default copy constructor and copy assignment operator are generated
    // Destructor is also generated by the compiler
private:
    double real_;
    double imag_;
};

int main() {
    Complex a(2.0, 3.0);
    Complex b; // Error: Default constructor is deleted
    // Complex c = a; // Default copy constructor is generated
    // Complex d;
    // d = a; // Default copy assignment operator is generated
    return 0;
}
